"""
Models package - all ORM models exported from unified_models (canonical source).
"""

from backend.models.unified_models import (
    Base,
    # Enums
    UserRoleEnum,
    OrderTypeEnum,
    OrderSideEnum,
    OrderStatusEnum,
    AssetTypeEnum,
    # Core models
    User,
    UserSession,
    Stock,
    Exchange,
    Sector,
    Industry,
    PriceHistory,
    Portfolio,
    Position,
    Transaction,
    Order,
    Alert,
    Watchlist,
    WatchlistItem,
    Recommendation,
    RecommendationPerformance,
    Fundamentals,
    Fundamental,  # backward-compat alias
    DividendHistory,
    News,
    PortfolioPerformance,
    ApiLog,
    SystemSettings,
    AuditLog,
    SystemMetrics,
    CostMetrics,
)

__all__ = [
    "Base",
    "UserRoleEnum",
    "OrderTypeEnum",
    "OrderSideEnum",
    "OrderStatusEnum",
    "AssetTypeEnum",
    "User",
    "UserSession",
    "Stock",
    "Exchange",
    "Sector",
    "Industry",
    "PriceHistory",
    "Portfolio",
    "Position",
    "Transaction",
    "Order",
    "Alert",
    "Watchlist",
    "WatchlistItem",
    "Recommendation",
    "RecommendationPerformance",
    "Fundamentals",
    "Fundamental",
    "DividendHistory",
    "News",
    "PortfolioPerformance",
    "ApiLog",
    "SystemSettings",
    "AuditLog",
    "SystemMetrics",
    "CostMetrics",
]
