#!/bin/bash
#
# Test Environment Setup Script
# Sets up PostgreSQL test database, Redis, and test fixtures
# Usage: ./scripts/setup-test-env.sh
#

set -e  # Exit on error

echo "==================================="
echo "Test Environment Setup"
echo "==================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
TEST_DB_NAME="investment_db_test"
TEST_DB_USER="postgres"
TEST_DB_PASSWORD="postgres"
TEST_DB_HOST="localhost"
TEST_DB_PORT="5432"
TEST_REDIS_HOST="localhost"
TEST_REDIS_PORT="6379"

# Step 1: Check if Docker is running
echo -e "${YELLOW}[1/8]${NC} Checking Docker..."
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}ERROR:${NC} Docker is not running. Please start Docker Desktop."
    exit 1
fi
echo -e "${GREEN}✓${NC} Docker is running"
echo ""

# Step 2: Start test infrastructure (PostgreSQL + Redis)
echo -e "${YELLOW}[2/8]${NC} Starting PostgreSQL and Redis for tests..."

# Check if services are already running
if docker ps | grep -q "investment.*postgres"; then
    echo -e "${GREEN}✓${NC} PostgreSQL container already running"
else
    echo "  Starting PostgreSQL..."
    docker-compose up -d postgres
    # Wait for PostgreSQL to be ready
    echo "  Waiting for PostgreSQL to be ready..."
    sleep 5
    until docker exec $(docker ps -q -f name=postgres) pg_isready -U postgres > /dev/null 2>&1; do
        echo "  Waiting for PostgreSQL..."
        sleep 2
    done
fi

if docker ps | grep -q "investment.*redis"; then
    echo -e "${GREEN}✓${NC} Redis container already running"
else
    echo "  Starting Redis..."
    docker-compose up -d redis
    sleep 2
fi

echo -e "${GREEN}✓${NC} Test infrastructure running"
echo ""

# Step 3: Create test database if it doesn't exist
echo -e "${YELLOW}[3/8]${NC} Creating test database..."

# Check if test database exists
DB_EXISTS=$(docker exec $(docker ps -q -f name=postgres) psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$TEST_DB_NAME'" 2>/dev/null || echo "0")

if [ "$DB_EXISTS" = "1" ]; then
    echo -e "${GREEN}✓${NC} Test database '$TEST_DB_NAME' already exists"
else
    echo "  Creating database '$TEST_DB_NAME'..."
    docker exec $(docker ps -q -f name=postgres) psql -U postgres -c "CREATE DATABASE $TEST_DB_NAME;" || {
        echo -e "${RED}ERROR:${NC} Failed to create test database"
        exit 1
    }
    echo -e "${GREEN}✓${NC} Test database created"
fi
echo ""

# Step 4: Install TimescaleDB extension
echo -e "${YELLOW}[4/8]${NC} Installing TimescaleDB extension..."
docker exec $(docker ps -q -f name=postgres) psql -U postgres -d $TEST_DB_NAME -c "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;" || {
    echo -e "${YELLOW}WARNING:${NC} TimescaleDB extension not available (optional)"
}
echo ""

# Step 5: Create .env.test file
echo -e "${YELLOW}[5/8]${NC} Creating .env.test configuration..."

cat > .env.test << EOF
# Test Environment Configuration
# Auto-generated by setup-test-env.sh

# Database
DATABASE_URL=postgresql://$TEST_DB_USER:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/$TEST_DB_NAME
TEST_DATABASE_URL=postgresql://$TEST_DB_USER:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/$TEST_DB_NAME

# Redis
REDIS_URL=redis://$TEST_REDIS_HOST:$TEST_REDIS_PORT/1
REDIS_PASSWORD=

# Testing flags
TESTING=true
DEBUG=true
LOG_LEVEL=WARNING

# Security (test keys only)
SECRET_KEY=test-secret-key-for-testing-only-do-not-use-in-production
JWT_SECRET_KEY=test-jwt-secret-key-for-testing-only
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7

# External API Keys (test/mock values)
ALPHA_VANTAGE_API_KEY=test_alpha_vantage_key
FINNHUB_API_KEY=test_finnhub_key
POLYGON_API_KEY=test_polygon_key
NEWS_API_KEY=test_news_key
YAHOO_FINANCE_API_KEY=test_yahoo_key

# Disable external API calls in tests
SKIP_EXTERNAL_API_TESTS=false
MOCK_EXTERNAL_APIS=true

# Test-specific settings
SKIP_SLOW_TESTS=false
TEST_DATA_SEED=true
EOF

echo -e "${GREEN}✓${NC} .env.test created"
echo ""

# Step 6: Run database migrations
echo -e "${YELLOW}[6/8]${NC} Running database migrations..."

# Load test environment
export $(cat .env.test | xargs)

# Check if alembic is available
if ! command -v alembic &> /dev/null; then
    echo "  Installing alembic..."
    pip install -q alembic
fi

# Run migrations
cd backend 2>/dev/null || true
alembic upgrade head || {
    echo -e "${YELLOW}WARNING:${NC} Migrations failed or not configured"
    echo "  You may need to run migrations manually:"
    echo "  cd backend && alembic upgrade head"
}
cd - > /dev/null 2>&1 || true

echo -e "${GREEN}✓${NC} Database migrations completed"
echo ""

# Step 7: Seed test data (optional)
echo -e "${YELLOW}[7/8]${NC} Seeding test data..."

if [ -f "scripts/seed_test_data.py" ]; then
    python scripts/seed_test_data.py || {
        echo -e "${YELLOW}WARNING:${NC} Test data seeding failed (optional)"
    }
    echo -e "${GREEN}✓${NC} Test data seeded"
else
    echo -e "${YELLOW}INFO:${NC} No test data seeding script found (optional)"
fi
echo ""

# Step 8: Verify connections
echo -e "${YELLOW}[8/8]${NC} Verifying connections..."

# Test PostgreSQL connection
if docker exec $(docker ps -q -f name=postgres) psql -U postgres -d $TEST_DB_NAME -c "SELECT 1;" > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} PostgreSQL connection successful"
else
    echo -e "${RED}ERROR:${NC} PostgreSQL connection failed"
    exit 1
fi

# Test Redis connection
if docker exec $(docker ps -q -f name=redis) redis-cli ping > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Redis connection successful"
else
    echo -e "${YELLOW}WARNING:${NC} Redis connection failed (non-critical)"
fi

echo ""
echo "==================================="
echo -e "${GREEN}✓ Test Environment Ready${NC}"
echo "==================================="
echo ""
echo "Database: postgresql://$TEST_DB_HOST:$TEST_DB_PORT/$TEST_DB_NAME"
echo "Redis: redis://$TEST_REDIS_HOST:$TEST_REDIS_PORT/1"
echo ""
echo "To run tests:"
echo "  export \$(cat .env.test | xargs)"
echo "  pytest backend/tests/ -v"
echo ""
echo "To run specific test categories:"
echo "  pytest backend/tests/ -v -m integration"
echo "  pytest backend/tests/ -v -m \"not slow\""
echo ""
echo "To stop test infrastructure:"
echo "  docker-compose down"
echo ""
