import React, { useState } from 'react';
import { Alert, AlertTitle, Box, Collapse, Link, Typography } from '@mui/material';

/**
 * InvestmentDisclaimer (T4.2 / D5 — DRAFT)
 *
 * Investment-disclaimer banner shown on recommendation/analysis surfaces so the
 * platform does not present algorithmic output as personalized investment advice.
 *
 * DRAFT: copy is scaffolding pending legal/counsel review (see
 * docs/legal/TERMS_OF_SERVICE.md and docs/legal/FORM_ADV_DECISION_MEMO.md). It
 * makes no claim of regulatory registration or fiduciary status.
 */
export interface InvestmentDisclaimerProps {
  /** "compact" renders a one-line warning with expandable detail (default);
   *  "full" renders the complete disclaimer body inline. */
  variant?: 'compact' | 'full';
  /** Override the surface noun used in the headline (e.g. "recommendations"). */
  context?: string;
  sx?: object;
}

const DISCLAIMER_PARAGRAPHS: readonly string[] = [
  'Not investment advice. The information and any BUY/SELL/HOLD signals shown here are generated by automated models for informational and educational purposes only. They are not personalized investment advice, an offer, or a solicitation to buy or sell any security.',
  'No fiduciary relationship. This platform is not a registered investment adviser and does not act as your fiduciary. It does not consider your individual financial situation, objectives, or risk tolerance. Consult a licensed financial professional before making any investment decision.',
  'No guarantee of accuracy or results. Market and fundamental data may be delayed or incomplete, and model outputs can be wrong. Past performance does not guarantee future results. All investments carry risk, including possible loss of principal.',
];

const InvestmentDisclaimer: React.FC<InvestmentDisclaimerProps> = ({
  variant = 'compact',
  context = 'analysis',
  sx,
}) => {
  const [expanded, setExpanded] = useState(variant === 'full');

  const body = (
    <Box>
      {DISCLAIMER_PARAGRAPHS.map((p, i) => (
        <Typography
          key={i}
          variant="body2"
          sx={{ mb: i < DISCLAIMER_PARAGRAPHS.length - 1 ? 1 : 0 }}
        >
          {p}
        </Typography>
      ))}
    </Box>
  );

  return (
    <Alert
      severity="warning"
      role="note"
      aria-label="Investment disclaimer"
      sx={{ mb: 2, ...sx }}
      data-testid="investment-disclaimer"
    >
      <AlertTitle>
        {`These ${context} are not investment advice`}
      </AlertTitle>

      {variant === 'full' ? (
        body
      ) : (
        <>
          <Typography variant="body2">
            Automated, informational only — not personalized advice and no
            guarantee of accuracy.{' '}
            <Link
              component="button"
              type="button"
              underline="always"
              onClick={() => setExpanded((v) => !v)}
              aria-expanded={expanded}
            >
              {expanded ? 'Show less' : 'Read full disclaimer'}
            </Link>
          </Typography>
          <Collapse in={expanded} unmountOnExit>
            <Box sx={{ mt: 1 }}>{body}</Box>
          </Collapse>
        </>
      )}
    </Alert>
  );
};

export default InvestmentDisclaimer;
